name: disocord_bot
description: A simple command-line application.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.14.2 <3.0.0'


dev_dependencies:
  lints: ^3.0.0
  

dependencies:
  dio: ^5.1.1
  dotenv: ^4.0.1
  supabase: ^1.6.3
  nyxx: ^6.0.2
  nyxx_commands: ^6.0.0
  riverpod: ^2.3.2