name: disocord_bot
description: A simple command-line application.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.14.2 <3.0.0'


dev_dependencies:
  lints: ^2.0.1
  

dependencies:
  dio: ^4.0.6
  dotenv: ^4.0.1
  supabase: ^1.1.0
  nyxx: ^4.4.0